---
- name: src depends
  pacman: name={{ item }} state=latest
  with_items:
    - lua
    - gtk2
    - curl
    - wget

- name: source build dependencies
  pacman: name={{ item }} state=latest
  with_items:
    - gcc
    - automake
    - ncurses
    - unzip
    - patch

- name: dvcs requirements
  pacman: name={{ item }} state=latest
  with_items:
    - mercurial
    - git
